spring.application.name=smartapart
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?user=postgres.cznmmrchdjlljmcznutn
spring.datasource.username=postgres.cznmmrchdjlljmcznutn
spring.datasource.password=MIoFK61SurRc5EWe
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
<<<<<<< HEAD
spring.jpa.show-sql=true
=======
spring.jpa.show-sql=true
>>>>>>> 702ad97ef6a49cc0e30f6a63c034e5774f551858
